name: APK Compilation (Android)

on:
  workflow_dispatch: 

env:
  JAVA_VERSION: "17.x"
  FLUTTER_VERSION: "3.5.1"

jobs:
  apk_compilation: 
    name: "APK Compilation"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: "gradle" 

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Install Flutter Dependencies
        run: flutter pub get

      - run: flutter build apk --debug --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apks
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-debug.apk
